In [24]:
import torch
import numpy as np

In [3]:
print(torch.__version__)
print(torch.version.cuda)

1.6.0
None


## Tensor could be seen as a more abstract object, in many ways, many of its operations are similar to numpy

In [4]:
a = torch.Tensor([[1, 2], [3, 4]])
a

tensor([[1., 2.],
        [3., 4.]])

In [5]:
a.type()

'torch.FloatTensor'

In [6]:
torch.Tensor(5, 5)

tensor([[0.0000e+00, 3.6893e+19, 0.0000e+00, 3.6893e+19, 2.1019e-44],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [7]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [8]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [9]:
torch.eye(2, 2)

tensor([[1., 0.],
        [0., 1.]])

In [12]:
# Generate a tensor with random values, which are within [0, 1]
torch.rand(5, 3)

tensor([[0.9910, 0.6164, 0.7079],
        [0.9708, 0.1331, 0.9752],
        [0.9084, 0.9951, 0.0590],
        [0.7318, 0.4683, 0.8242],
        [0.3880, 0.5425, 0.5820]])

In [18]:
# same shape as a given tensor
a = torch.Tensor(2, 3)
# torch.ones_like(a)
torch.zeros_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
torch.Tensor(2, 2).uniform_(-1, 1)

tensor([[-0.1364, -0.2170],
        [-0.1866, -0.6179]])

In [22]:
print(torch.arange(0, 10))  # within [0, 10), same as Python
print(torch.arange(0, 10, 2))
print(torch.linspace(0, 10, 5))  # divide the range evenly over [0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [23]:
torch.randperm(10)  # Returns a random permutation

tensor([4, 9, 6, 0, 5, 3, 2, 7, 8, 1])

In [26]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [30]:
torch.tensor([[1, 2], [3, 4]])

tensor([[1, 2],
        [3, 4]])

In [3]:
# Tensor attribute
tensor = torch.rand(3,4)
print(tensor.shape, tensor.device, tensor.dtype)

torch.Size([3, 4]) cpu torch.float32


In [33]:
dev = torch.device("cpu")  # "cuda"
a = torch.tensor([2, 2], dtype=torch.float32, device=dev)
print(a, a.type())

tensor([2., 2.]) torch.FloatTensor


In [36]:
# Construct a sparse tensor in coordinate format, only store coordinates of non-zero
# values to save space
# In the example below, 1 is stored at [0,1], 2 at [1,1], and 3 at [2,2]
i = torch.tensor([[0, 1, 2], [0, 1, 2]])  # indices of non-zero entry, they are on the diagnal in this case
v = torch.tensor([1, 2, 3])
b = torch.sparse_coo_tensor(i, v, (3, 3))
b.to_dense()

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

## Arithmetic 
### (mul is elementwise). Note that method end with '_' (e.g., add_(), sub_()) are in-place operation. a.add_(b) is equivalent to a += b

In [40]:
# a +, -, *, / b == a.add, sub, mul, div(b) == torch.add, sub, mul, div(a, b, 
a = torch.tensor([1, 2, 3], dtype=float)
b = torch.ones_like(a)
print(torch.pow(a, 2))  # torch.pow(a, 2) == a.pow(2) == a ** 2 != a.pow_(2)
print(torch.exp(a))  # e^a
print(torch.log2(a))
print(torch.log10(a))
print(torch.log(a))  # ln(a)
print(torch.sqrt(a))  # a.sqrt()
print(a.add_(b))  # a += b
print(a + b)

tensor([1., 4., 9.], dtype=torch.float64)
tensor([ 2.7183,  7.3891, 20.0855], dtype=torch.float64)
tensor([0.0000, 1.0000, 1.5850], dtype=torch.float64)
tensor([0.0000, 0.3010, 0.4771], dtype=torch.float64)
tensor([0.0000, 0.6931, 1.0986], dtype=torch.float64)
tensor([1.0000, 1.4142, 1.7321], dtype=torch.float64)
tensor([2., 3., 4.], dtype=torch.float64)
tensor([3., 4., 5.], dtype=torch.float64)


In [41]:
# 2-D matrix operation, note that when matrices have more than 2 dimensions, only the last 2 is dotted
A = torch.ones(2, 3)
B = torch.ones(3, 2)
torch.matmul(A, B)  # torch.mm(A, B) = torch.matmul(A, B) = A @ B

tensor([[3., 3.],
        [3., 3.]])

In [8]:
t1 = torch.cat([tensor, tensor],dim=1)
t1

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [43]:
# Note that if A or B has more than 2 dimension, only the last 2 dimensions is computed
A = torch.ones(1,2,3,4)
B = torch.ones(4,3)
print(A.matmul(B).shape)

torch.Size([1, 2, 3, 3])


In [48]:
a = torch.ones(2, 3)
b = torch.rand(1, 3)
print(a + 10)
print(a + b)
print(torch.rand(2, 1, 1) + torch.rand(3))

tensor([[11., 11., 11.],
        [11., 11., 11.]])
tensor([[1.8131, 1.4617, 1.2926],
        [1.8131, 1.4617, 1.2926]])
tensor([[[1.4746, 1.1201, 1.2348]],

        [[1.5661, 1.2116, 1.3262]]])


### Number issues

In [50]:
a = torch.rand(2, 2) * 10
print("Original a:", a)
print(torch.floor(a))
print(torch.ceil(a))
print(torch.round(a))
print(torch.trunc(a))  # Throw decimal part
print(torch.frac(a))  # Throw interger part
print(a % 2)

Original a: tensor([[2.5497, 2.0306],
        [9.9834, 2.7883]])
tensor([[2., 2.],
        [9., 2.]])
tensor([[ 3.,  3.],
        [10.,  3.]])
tensor([[ 3.,  2.],
        [10.,  3.]])
tensor([[2., 2.],
        [9., 2.]])
tensor([[0.5497, 0.0306],
        [0.9834, 0.7883]])
tensor([[0.5497, 0.0306],
        [1.9834, 0.7883]])


In [57]:
# Return mask tensor (elementwise)
a = torch.rand(2, 3)
print(torch.isfinite(a))
print(torch.isfinite(a/0))
print(torch.isinf(a/0))
print(torch.isnan(a))

tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])


### Comparison

In [67]:
a = torch.tensor([[1, 3, 5], [2, 4, 6]])
b = torch.tensor([[1, 0, 0], [7, 7, 7]])
print(torch.eq(a, b))  # return a mask tensor with same shape as input (only compare value)
print(torch.equal(a, b))  # return 1 value (compare both value and shape)
print(torch.ge(a, b))
print(torch.gt(a, b))
print(torch.le(a, b))
print(torch.lt(a, b))
print(torch.ne(a, b))

tensor([[ True, False, False],
        [False, False, False]])
False
tensor([[ True,  True,  True],
        [False, False, False]])
tensor([[False,  True,  True],
        [False, False, False]])
tensor([[ True, False, False],
        [ True,  True,  True]])
tensor([[False, False, False],
        [ True,  True,  True]])
tensor([[False,  True,  True],
        [ True,  True,  True]])


In [60]:
# Trigonometric
a = torch.ones(2, 3)
torch.cos(a)  # sin(), tan(), ...

tensor([[0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403]])

In [63]:
# Other mathematical funtions that used frequently
print(torch.abs(a))
print(torch.sigmoid(a))
print(torch.sign(a))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7311, 0.7311, 0.7311],
        [0.7311, 0.7311, 0.7311]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [71]:
a = torch.tensor([[2, 4, 6], [5, 3, 1]])
print(torch.sort(a, dim=1, descending=False))
print(torch.sort(a, dim=0, descending=False))
print(torch.topk(a, 1))
print(torch.kthvalue(a, k=1, dim=0))
print(torch.kthvalue(a, k=1, dim=1))

torch.return_types.sort(
values=tensor([[2, 4, 6],
        [1, 3, 5]]),
indices=tensor([[0, 1, 2],
        [2, 1, 0]]))
torch.return_types.sort(
values=tensor([[2, 3, 1],
        [5, 4, 6]]),
indices=tensor([[0, 1, 1],
        [1, 0, 0]]))
torch.return_types.topk(
values=tensor([[6],
        [5]]),
indices=tensor([[2],
        [0]]))
torch.return_types.kthvalue(
values=tensor([2, 3, 1]),
indices=tensor([0, 1, 1]))
torch.return_types.kthvalue(
values=tensor([2, 1]),
indices=tensor([0, 2]))


## Statistic

In [78]:
a = torch.tensor([[2, 4, 6], [5, 3, 1]], dtype=float)
print(torch.mean(a))
print(torch.sum(a))  # argmin(a)
print(torch.sum(a, dim=1))
print(torch.max(a))  # argmax(a)
print(torch.prod(a))  # product
print(torch.std(a))
print(torch.var(a))
# median(), mode(), histc(), bincount()
print()
print(torch.argmax(a, dim=0))

tensor(3.5000, dtype=torch.float64)
tensor(21., dtype=torch.float64)
tensor([12.,  9.], dtype=torch.float64)
tensor(6., dtype=torch.float64)
tensor(720., dtype=torch.float64)
tensor(1.8708, dtype=torch.float64)
tensor(3.5000, dtype=torch.float64)

tensor([1, 0, 0])


In [82]:
torch.manual_seed(1)
mean = torch.rand(1, 2)
std = torch.rand(1, 2)
a = torch.normal(mean, std)
a

tensor([[0.7825, 0.7358]])

In [84]:
# Distance measure: widely used in loss function
a = torch.rand(2, 5)
b = torch.rand(2, 5)
print(a, b)
print(torch.dist(a, b, p=1))  # abs(a - b)
print(torch.dist(a, b, p=2))  # sqrt((a - b)^2)
print(torch.dist(a, b, p=3))  # cube_root((a - b)^3)

tensor([[0.6387, 0.5247, 0.6826, 0.3051, 0.4635],
        [0.4550, 0.5725, 0.4980, 0.9371, 0.6556]]) tensor([[0.3138, 0.1980, 0.4162, 0.2843, 0.3398],
        [0.5239, 0.7981, 0.7718, 0.0112, 0.8100]])
tensor(2.7111)
tensor(1.1448)
tensor(0.9725)


In [8]:
t1 = torch.cat([tensor, tensor],dim=1)
t1

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
# Bridge with numpy
print(tensor)
print(tensor.numpy())
print(torch.from_numpy(tensor.numpy()))

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
